//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.12 at 01:33:38 PM CST 
//


package org.yiwan.webcore.locator;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="locatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WebElement"/&gt;
 *     &lt;enumeration value="WebEdit"/&gt;
 *     &lt;enumeration value="WebButton"/&gt;
 *     &lt;enumeration value="WebCheckBox"/&gt;
 *     &lt;enumeration value="WebRadioGroup"/&gt;
 *     &lt;enumeration value="WebFile"/&gt;
 *     &lt;enumeration value="WebList"/&gt;
 *     &lt;enumeration value="WebTable"/&gt;
 *     &lt;enumeration value="WebTableRow"/&gt;
 *     &lt;enumeration value="WebTableColumn"/&gt;
 *     &lt;enumeration value="WebTableCell"/&gt;
 *     &lt;enumeration value="Image"/&gt;
 *     &lt;enumeration value="Frame"/&gt;
 *     &lt;enumeration value="Link"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "locatorType")
@XmlEnum
public enum LocatorType {

    @XmlEnumValue("WebElement")
    WEB_ELEMENT("WebElement"),
    @XmlEnumValue("WebEdit")
    WEB_EDIT("WebEdit"),
    @XmlEnumValue("WebButton")
    WEB_BUTTON("WebButton"),
    @XmlEnumValue("WebCheckBox")
    WEB_CHECK_BOX("WebCheckBox"),
    @XmlEnumValue("WebRadioGroup")
    WEB_RADIO_GROUP("WebRadioGroup"),
    @XmlEnumValue("WebFile")
    WEB_FILE("WebFile"),
    @XmlEnumValue("WebList")
    WEB_LIST("WebList"),
    @XmlEnumValue("WebTable")
    WEB_TABLE("WebTable"),
    @XmlEnumValue("WebTableRow")
    WEB_TABLE_ROW("WebTableRow"),
    @XmlEnumValue("WebTableColumn")
    WEB_TABLE_COLUMN("WebTableColumn"),
    @XmlEnumValue("WebTableCell")
    WEB_TABLE_CELL("WebTableCell"),
    @XmlEnumValue("Image")
    IMAGE("Image"),
    @XmlEnumValue("Frame")
    FRAME("Frame"),
    @XmlEnumValue("Link")
    LINK("Link");
    private final String value;

    LocatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocatorType fromValue(String v) {
        for (LocatorType c: LocatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
